############################
## CHANGE THESE
############################

#baseURL: "https://atisz7.github.io/qubtisz"
baseURL: "http://localhost:1313/"
title: qubtisz

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
