############################
## CHANGE THESE
############################

baseURL: "https://atisz7.github.io/qubtisz"
title: qubtisz

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
